baseURL = "https://JimGian.github.io/Angioedema/"
languageCode = "en-us"
title = "Angioedema"
theme = "ananke"
publishDir = "docs"

[params]
  custom_css = ["css/custom.css"]
  description = "Educational website providing clear, accessible information about angioedema for the general public."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "conditions"
    name = "Conditions"
    url = "/conditions/"
    weight = 2
