baseURL = "https://JimGian.github.io/Angioedema/"
languageCode = "en-us"
title = "Home"
theme = "ananke" 

[params]
  custom_css = ["custom.css"]
  site_logo = "themes/ananke/static/images/nna.png"
  text_color = "black"

  [params.hero]
    heading = "Understanding Angioedema"
    text = "Explore clear, evidence-based explanations of the different types of angioedema â€” symptoms, diagnosis, and treatment."
    button_text = "Explore Conditions"
    button_url = "/conditions/"
    background_image = "images/hero-bg.jpg" # place this image in /static/images/

  description = "Medical information and guidance about angioedema, including histaminergic, bradykinin-mediated, and idiopathic forms."
  author = "Dr. Jim Gian"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Angioedema"
    site_logo = "themes/ananke/static/images/nna.png"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "conditions"
    name = "Articles"
    site_logo = "themes/ananke/static/images/nna.png"
    url = "/conditions/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About us"
    site_logo = "themes/ananke/static/images/nna.png"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    site_logo = "themes/ananke/static/images/nna.png"
    url = "/contact/"
    weight = 4
