baseURL = "https://JimGian.github.io/Angioedema/"
languageCode = "en-us"
title = "Angioedema Information Center"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["custom.css"]

  site_logo = "images/nna.png"

  description = "Clear, accessible information about angioedema for the general public."

  background_color_class = "bg-dark-blue"

  cover_dimming_class = "bg-black-40"

  body_classes = "avenir bg-near-white"

  recent_posts_number = 0

  text_color = "black"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Angioedema"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "conditions"
    name = "Articles"
    url = "/conditions/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About us"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
