baseURL = "https://JimGian.github.io/Angioedema/"
languageCode = "en-us"
title = "Angioedema"
theme = "ananke"
publishDir = "docs"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "Conditions"
    name = "Conditions"
    url = "/Conditions/"
    weight = 2