baseURL = "https://JimGian.github.io/Angioedema/"
languageCode = "en-us"
title = "Home"
theme = "ananke" 

[params]
  custom_css = ["custom.css"]
  site_logo = "themes/ananke/static/images/nna.png"
  text_color = "black"

[params.hero]
  heading = "Welcome to Angioedema Info"
  text = "Learn about the causes, symptoms, and treatments of various forms of angioedema."
  button_text = "Explore Conditions"
  button_url = "/conditions/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Angioedema"
    site_logo = "themes/ananke/static/images/nna.png"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "conditions"
    name = "Articles"
    site_logo = "themes/ananke/static/images/nna.png"
    url = "/conditions/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About us"
    site_logo = "themes/ananke/static/images/nna.png"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    site_logo = "themes/ananke/static/images/nna.png"
    url = "/contact/"
    weight = 4


[[params.social]]
  name = "github"
  url = "https://github.com/YourUsername"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/yourprofile"


[taxonomies]
  tag = "tags"
  category = "categories"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = "dracula"  
    noClasses = false

[deployment]
  [[deployment.targets]]
    name = "production"
    URL = "s3://my-bucket-name?region=us-west-2"