baseURL = "https://JimGian.github.io/Angioedema/"
languageCode = "en-us"
title = "Angioedema"
theme = "ananke"
publishDir = "docs"

[params]
  custom_css = ["custom.css"]
  site_logo = "'themes/ananke/images/gohugo-default-sample-hero-image.jpg'"
  text_color = "green"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "conditions"
    name = "Conditions"
    url = "/conditions/"
    weight = 2
